/* All fixtures are fictional and generated relative to the demo's first start. */
(()=>{
  const date=(offset=0)=>{const d=new Date();d.setDate(d.getDate()+offset);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
  const assets=[['press','Demopresse 01','D-101','Halle A'],['compressor','Kompressor 01','D-102','Technikraum'],['conveyor','Förderband 01','D-103','Halle B'],['thermal-a','Wärmeanlage A','D-104','Halle C'],['thermal-b','Wärmeanlage B','D-105','Halle C']].map(([id,name,number,location])=>({id:`demo_${id}`,name,number,location,notes:'Fiktive Beispielanlage.'}));
  const employees=['Alex Beispiel','Robin Muster','Kim Demo','Sam Beispiel'].map((name,i)=>({id:`demo_person_${i}`,name,dept:i%2?'Elektrik':'Mechanik',notes:'Fiktive Person.'}));
  function createState(){
    const now=new Date().toISOString();
    const tasks=[['Hydraulikleitung prüfen',0,0,0,'high','work'],['Filterwechsel',1,2,-2,'normal','maintenance'],['Antrieb ausrichten',2,1,1,'normal','work'],['Temperaturfühler kontrollieren',3,3,2,'normal','work'],['Sicherheitsprüfung',4,1,4,'high','maintenance'],['Riemenspannung prüfen',2,0,7,'normal','maintenance'],['Druckluftleckage beseitigen',1,2,0,'normal','work'],['Schutzgitter instand setzen',0,0,-5,'normal','work']].map(([title,a,e,day,priority,kind],i)=>({id:`demo_task_${i}`,title,assetId:assets[a].id,employeeId:employees[e].id,dateFrom:date(day),dateTo:date(day),time:i===0?'09:00':'',priority,kind,status:i===7?'done':'open',doneComment:i===7?'Beispiel: Funktion erfolgreich geprüft.':'',doneAt:i===7?date(-4):null,notes:'Demonstrationsauftrag – frei erfundene Beispieldaten.',sapRef:i===0?'DEMO-0001':'',decisionNeeded:i===2,blocker:i===2?'Ersatzantrieb freigeben':'',sourcePlanId:null}));
    return {version:2,meta:{createdAt:now,updatedAt:now,demo:true,backend:'browser-demo'},assets:structuredClone(assets),employees:structuredClone(employees),tasks,maintenancePlans:[{id:'demo_plan_1',title:'Schmierung und Sichtprüfung',assetId:assets[0].id,employeeId:employees[0].id,intervalValue:2,intervalUnit:'weeks',nextDue:date(3),notes:'Fiktiver Wartungsplan.',active:true},{id:'demo_plan_2',title:'Druckluftanlage warten',assetId:assets[1].id,employeeId:employees[2].id,intervalValue:1,intervalUnit:'months',nextDue:date(6),notes:'Fiktiver Wartungsplan.',active:true}],absences:[{id:'demo_abs_1',employeeId:employees[2].id,type:'vacation',start:date(3),end:date(6),notes:'Beispielurlaub'},{id:'demo_abs_2',employeeId:employees[1].id,type:'shift',start:date(),end:date(4),notes:'Spätschicht'}],settings:{weekMode:'week',showWeekends:true}};
  }
  function monitoring(lineB=false){return {schemaVersion:1,module:lineB?'umwaelzer-lineb':'umwaelzer',assetId:assets[lineB?4:3].id,assetName:assets[lineB?4:3].name,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),technical:{},sockets:(lineB?['10.1','10.2','11.1','11.2','12.1','12.2','13.1']:['S 1.1','S 1.2','S 2.1','S 2.2','S 3.1','S 3.2','S 4.1','S 4.2']).map((id,i)=>({id,history:i<3?[{id:`demo_history_${i}`,inDate:date(-30-i*10),outDate:'',motor:`DEMO-M${i+1}`,fan:`DEMO-L${i+1}`,note:'Fiktiver Einbau zur Demonstration.'}]:[],hood:{welded:i===0,date:i===0?date(-10):'',repairs:[]}})),defectiveFans:[]};}
  const parts=['Hydraulikfilter','Rillenkugellager','Drucksensor','Keilriemen','Schütz','Dichtungssatz','Temperaturfühler','Lüftermotor'].map((Bezeichnung,i)=>({'Material Nr.':`DEMO-${1000+i}`,Bezeichnung,Anlage:assets[i%assets.length].name,Aggregat:i%2?'Antrieb':'Versorgung','IST [Stck.]':String([2,0,4,1,8,3,0,2][i]),'SOLL [Stck.]':'4',Lagerort:`Demo-Regal ${i+1}`,Lieferant:'Beispiellieferant','Einzelpreis [in €]':String(20+i*15),Bemerkung:'Fiktiver Ersatzteilbestand.','Quelle Datei':'Demo-Ersatzteile.xlsx','Quelle Blatt':'Demo','Excel Zeile':i+2,__sourceKey:'demo',__sourceFileName:'Demo-Ersatzteile.xlsx',__excelRowIndex:i+1}));
  globalThis.PlanungDemo={createState,monitoring,parts,date};
})();
